from pydantic import BaseModel ,Field
from typing import Annotated,Literal
from operator import add

class AgentSchema(BaseModel):
    messages:Annotated[list,add]=Field(...,description="List of messages to be processed by the agent")
    #Annotated is just a way to tell how the messages shoukld behave like the messages should go on adding in the list
    user_question:str=Field(...,description="the original question asked by the user")
    curated_ques:str=Field(...,description="curated user questions")
    prompt_query_context:str=Field(...,description="a detailed prompt with sql db context that will help agent to genearte the sql query")
    is_safe:Literal["Yes","No"]=Field(...,description="inidicates whether the generated sql query is safe or not")
    generated_sql_query:str=Field(...,description="the sql query generated by the agent")
    comments:str=Field(...,description="comments regarding the generated sql query")
    sql_query_execution_result:str=Field(...,description="the result of executing the generated sql query on the database")
    final_answer:str=Field(...,description="the final answer generated by the agent based on the sql query  ")

class JudgeSchema(BaseModel):
    answer:Literal["Yes","No"]=Field(...,description="Indicates whether the generated sql query is safe or not")
    comments:str=Field(...,description="additional comments or the feedback regarding the sql query from the llm judge")

